##############################################################
# Http requests for elasticSearch
##############################################################
### Définition des variables globales

@hostname = "http://localhost:3000"

# #############
#  Parameters #
# #############
@text = "love"
@limit = "10"
@page = "1"

# localhost:3000/quotes?text=love&limit=3&page=2
## 
GET http://localhost:3000/quotes?text=moss&limit=10&page=1 HTTP/1.1
    
### 
GET http://localhost:3000/quotes?text=work&limit=10 HTTP/1.1

####
#### Get list of quotes by parameter 
#### 
GET {{hostname}}/quotes?text={{text}}&limit={{limit}}&page={{page}} HTTP/1.1



