# Imagem desenvolvida para ser a base de projetos usando node.js
# na construção de APIs. 
FROM node:13.12.0-alpine 
MAINTAINER Julio Torres 

WORKDIR /app/src

# Instalação dos pacotes básicos de desenvolvimento de API
CMD npm install nodemon body-parser ngrok swagger-ui-express

copy README.md ./